'use strict';

/*************************************
 * edit user profile
 * *************************************/

module.exports = {
    DISPLAY: {
        TITLE: "COMPANY",
        CONTROLS: {
            FILTER_LABEL: "Filter",
            CLEAR_LABEL: "Clear",
            ACTION_LABEL: "Actions",
            NEW_COMPANY: "New Company",
            MODIFY_COMPANY: "Modify Company",
            DELETE_COMPANY: "Delete Company",
            FILTER_SERVICE_TYPE_PLACEHOLDER: "Service Type",
            FILTER_STATE_LABEL: "Select State",
            APPLY_FILTER_LABEL: "Apply",
            CLEAR_FILTER_LABEL: "Clear"
        },
        HELP_LABEL: 'Help',
        DESCRIPTION: 'Manage all companies created under Aglive.',
        FILTER_TITLE: 'Filters',
        DELETE_CONFIRMATION_MESSAGE: "Are you sure you want to delete?",
        DELETE_SUCCESS: 'Contact(s) deleted successfully.',
        SET_PASSWORD: {
            PASSWORD_SET_SUCCESS: "Password set successfully",
            TITLE: "SET PASSWORD",
            CONTROLS: {
                LOGGEDIN_PASSWORD_LABEL: "Your Current Password",
                LOGGEDIN_PASSWORD_PLACE_HOLDER: "Your Current Password",
                LOGGEDIN_PASSWORD_REQ_MESSAGE: "Please enter Your Current Password",
                NEW_PASSWORD_PLACE_HOLDER: "New Password",
                NEW_PASSWORD_LABEL: "New Password",
                CONFIRM_PASSWORD_PLACE_HOLDER: "Re-enter New Password",
                CONFIRM_PASSWORD_LABEL: "Re-enter New Password",
                MUST_CHAR_REQ_MESSAGE: "New Password must be at least 8 characters",
                NEW_PASSWORD_REQ_MESSAGE: "Please enter New Password",
                CONFIRM_PASSWORD_REQ_MESSAGE: "Please confirm New Password",
                CONFIRM_PASSWORD_VALIDATE_MESSAGE: "Password Not Match",
                SUBMIT_LABEL: "Save",
                CLOSE_LABEL: "Close"
            }
        }
    },
    DETAIL: {
        ADD_TITLE: "ADD COMPANY",
        MODIFY_TITLE: "MODIFY COMPANY",
        CONTROLS: {
            SAVE_LABEL: "SAVE",
            BACK_LABEL: "Reset",
            UPLOAD_LABEL: "Upload",
            DELETE_LABEL: "Delete",
            CLEAR_LABEL: "Clear",
            ACTION_LABEL: "Actions",
            ADD_REGION_LABEL: 'Add Region',
            ADD_BUSINESS_LABEL: 'Add Business Unit',
            MODIFY_REGION_LABEL: 'Modify Region',
            MODIFY_BUSINESS_LABEL: 'Modify Business Unit',
            DELETE_REGION_LABEL: 'Delete Region',
            DELETE_BUSINESS_LABEL: 'Delete Business Unit',
            COMPANY_COMPANYNAME_PLACEHOLDER: "Enter Company Name",
            COMPANY_COMPANYNAME_LABEL: "Company Name",
            COMPANY_COMPANYNAME_REQ_MESSAGE: "Please enter Company Name",
            COMPANY_SHORT_CODE_PLACEHOLDER: "Enter Short Code",
            COMPANY_SHORT_CODE_LABEL: "Short Code",
            COMPANY_SHORT_CODE_REQ_MESSAGE: "Please enter Short Code",
            COMPANY_EMAIL_PLACEHOLDER: "Enter Email",
            COMPANY_EMAIL_LABEL: "Email",
            COMPANY_EMAIL_REQ_MESSAGE: "Please enter Email",
            COMPANY_WEBSITE_PLACEHOLDER: "Enter Website",
            COMPANY_WEBSITE_LABEL: "Website",
            COMPANY_MOBILE_PLACEHOLDER: "Enter Mobile Number",
            COMPANY_MOBILE_LABEL: "Mobile Number",
            COMPANY_TELEPHONE_PLACEHOLDER: "Enter Telephone Number",
            COMPANY_TELEPHONE_LABEL: "Telephone Number",
            COMPANY_FAX_PLACEHOLDER: "Enter Fax Number",
            COMPANY_FAX_LABEL: "Fax Number",
            COMPANY_SERVICE_TYPE_PLACEHOLDER: "Select Service Type",
            COMPANY_SERVICE_TYPE_LABEL: "Service Type",
            COMPANY_SERVICE_TYPE_REQ_MESSAGE: "Please select Service Type",
            COMPANY_ADDRESS_PLACEHOLDER: "Enter Business Address",
            COMPANY_ADDRESS_LABEL: "Business Address",
            COMPANY_ADDRESS_REQ_MESSAGE: "Please enter Business Address",
            COMPANY_POSTALADDRESS_PLACEHOLDER: "Enter Postal Address",
            COMPANY_POSTALADDRESS_LABEL: "Postal Address",
            COMPANY_BUSINESS_COUNTRY_PLACEHOLDER: "Select Business Country",
            COMPANY_BUSINESS_COUNTRY_REQ_MESSAGE: "Please select Business Country",
            COMPANY_POSTAL_COUNTRY_PLACEHOLDER: "Select Postal Country",
            COMPANY_POSTAL_COUNTRY_REQ_MESSAGE: "Please select Postal Country",
            COMPANY_SUBURB_PLACEHOLDER: "Enter Suburb",
            COMPANY_SUBURB_LABEL: "Suburb",
            COMPANY_POSTALSUBURB_PLACEHOLDER: "Enter Suburb",
            COMPANY_POSTALSUBURB_LABEL: 'Suburb',
            COMPANY_STATE_PLACEHOLDER: "Enter State",
            COMPANY_STATE_LABEL: "State",
            COMPANY_POSTALSTATE_PLACEHOLDER: "Enter State",
            COMPANY_POSTALSTATE_LABEL: "State",
            COMPANY_POSTCODE_PLACEHOLDER: "Enter Post Code",
            COMPANY_POSTCODE_LABEL: "Post Code",
            COMPANY_POSTALPOSTCODE_PLACEHOLDER: "Enter Post Code",
            COMPANY_POSTALPOSTCODE_LABEL: "Post Code",
            COMPANY_ABN_PLACEHOLDER: "Enter ABN",
            COMPANY_ABN_LABEL: "ABN",
            COMPANY_ACN_PLACEHOLDER: "Enter ACN",
            COMPANY_ACN_LABEL: "ACN",
            COMPANY_LABEL: "Company",
            COMPANY_REQ_MESSAGE: "Please select Company",
            EMAIL_VALIDATE_MESSAGE: 'Invalid email address',
            COMPANY_REGION_MANAGER_PLACEHOLDER: 'Select Region Manager',
            COMPANY_REGION_MANAGER_LABEL: 'Region Manager',
            COMPANY_ASST_REGION_MANAGER_PLACEHOLDER: 'Select Asst. Region Manager',
            COMPANY_ASST_REGION_MANAGER_LABEL: 'Asst. Region Manager',
            COMPANY_BUSINESS_MANAGER_PLACEHOLDER: 'Select Business Manager',
            COMPANY_BUSINESS_MANAGER_LABEL: 'Business Manager',
            COMPANY_ASST_BUSINESS_MANAGER_PLACEHOLDER: 'Select Asst. Business Manager',
            COMPANY_ASST_BUSINESS_MANAGER_LABEL: 'Asst. Business Manager',
            REGION_NAME_PLACEHOLDER: 'Enter Region Name',
            REGION_NAME_LABEL: 'Region Name',
            REGION_NAME_REQ_MESSAGE: 'Please enter Region Name',
            REGION_SHORTCODE_PLACEHOLDER: 'Enter Short Code',
            REGION_SHORTCODE_LABEL: 'Short Code',
            REGION_SHORTCODE_REQ_MESSAGE: 'Please enter Short Code',
            BUSINESS_NAME_PLACEHOLDER: 'Enter Business Name',
            BUSINESS_NAME_LABEL: 'Business Name',
            BUSINESS_NAME_REQ_MESSAGE: 'Please enter Business Name',
            BUSINESS_SHORTCODE_PLACEHOLDER: 'Enter Short Code',
            BUSINESS_SHORTCODE_LABEL: 'Short Code',
            BUSINESS_SHORTCODE_REQ_MESSAGE: 'Please enter Short Code',
            BUSINESS_REGION_PLACEHOLDER: 'Select Region',
            BUSINESS_REGION_LABEL: 'Region',
            BUSINESS_REGION_REQ_MESSAGE: 'Please select Region',
        },
        HELP_LABEL: 'Help',
        DESCRIPTION: 'Update company details.',
        COMPANY_TAB_TITLE: 'Company',
        REGION_TAB_TITLE: 'Region',
        BUSINESSUNIT_TAB_TITLE: 'Business Unit',
        SUBSCRIPTION_TAB_TITLE: 'Subscription',
        CONTACT: require('./contact'),
        PROPERTY: require('./property'),
        INVALID_UUID: "Invalid UUID passed.",
        LOGO_LABEL: "Logo",
        PICTURE_DELETE_SUCCESS: "Company Logo deleted successfully",
        SAVE_COMPANY_VALIDATION: "Please save company first",
        DUPLICATE_EMAIL_VALIDATION: "Email already register with another company",
        DUPLICATE_COMPANY_VALIDATION: "Company Name already exist",
        DUPLICATE_REGION_VALIDATION: "Region Name already exist",
        DUPLICATE_BUSINESSUNIT_VALIDATION: "Business Unit Name already exist",
        SAME_REGION_MANAGER_ERROR: 'Region Manager can not be same as Asst. Region Manager.',
        SAME_ASST_REGION_MANAGER_ERROR: 'Asst. Region Manager can not be same as Region Manager.',
        SAME_BUSINESS_MANAGER_ERROR: 'Business Manager can not be same as Asst. Business Manager.',
        SAME_ASST_BUSINESS_MANAGER_ERROR: 'Asst. Business Manager can not be same as Business Manager.',
        DELETE_CONFIRMATION_MESSAGE: "Are you sure you want to delete?",
        SAVE_CONFIRMATION_MESSAGE: "Are you sure you want to save?",
        DELETE_BUSINESS_SUCCESS: 'Business(es) deleted successfully.',
        DELETE_REGION_SUCCESS: 'Region(s) deleted successfully.',
        VALIDATION: {
            1122: "Please enter Company Name.",
            1123: "Please enter Short Code.",
            1124: "Please enter Email.",
            1125: "Please enter Business Address.",
            1126: "Please select Business Country.",
            1127: "Please select Postal Country.",
            1128: "Please select Company.",
            1129: "Company Name should not exceed 250 characters.",
            1130: "Short Code should not exceed 20 characters.",
            1131: "Email should not exceed 100 characters."
        }
    }
};