'use strict';

/*************************************
 * e-NVD sub pages
 * *************************************/

module.exports = {
    'DISPLAY': {
        CONTROLS: {
            SELECTALL_LABEL: "Select All",
            CLEAR_LABEL: "Clear",
            ACTIVATE_LABEL: "Activity",
            FILTER_LABEL: "Filter",
            ACTION_LABEL: 'Actions',
            APPLY_FILTER_LABEL: "Apply",
            CLEAR_FILTER_LABEL: "Clear",
            CLEAR_FILTER_LABEL1: "Clear Filter",
            MODIFY_ENVD_LABEL: 'Modify eNVD',
            DELETE_ENVD_LABEL: 'Delete eNVD',
            PICKUP_ENVD_LABEL: 'Pickup eNVD',
            DELIVER_ENVD_LABEL: 'Deliver eNVD',
            UPDATE_BUYER_LABEL: 'Update Buyer',
            VIEW_GROUP_LABEL: 'View',
            VIEW_ENVD_LABEL: 'View eNVD',
            VIEW_WAYBILL_LABEL: 'View Waybill',
            VIEW__NT_ENVD_LABEL: `View NT's eNVD`,
            VIEW_SA_ENVD_LABEL: `View SA's eNVD`,
            VIEW_NFAS_STATEMENT_LABEL: 'View NFAS Statement',
            VIEW_MSA_STATEMENT_LABEL: 'View MSA Statement',
            VIEW_AUS_MEAT_STATEMENT_LABEL: 'View AUS Meat Statement',
            VIEW_HEALTH_STATEMENT_LABEL: 'View Health Statement',
            VIEW_ATTCHED_DOCUMENTS_LABEL: 'View Attached Documents',
            NLIS_GROUP_LABEL: 'NLIS',
            SUBMIT_NLIS_LABEL: 'Submit to NLIS',
            SUBMIT_MOVEMENT_LABEL: 'Submit Movement',
            RETRIEVE_ENVD_LABEL: 'Retrieve eNVD from NLIS',
            NOTIFICATION_GROUP_LABEL: 'Notification',
            SEND_EMAIL_LABEL: 'Send Email',
            SEND_SMS_LABEL: 'Send SMS',
            SEND_FAX_LABEL: 'Send Fax',


            NONE: "None",
            ASSIGN_TO_ME: "Assign to me",
            ASSIGN_TO_OTHER: "Assign to other",
            FROMDATE_PLACEHOLDER: "From Date",
            TODATE_PLACEHOLDER: "To Date",
            RETRIEVED_ENVD_LABEL: "Retrieved eNVDs from NLIS",
            SPECIES_PLACEHOLDER: 'Select Species',
            SPECIES_LABEL: 'Species',
            ENVD_TYPE_PLACEHOLDER: "Select eNVD Type",
            ENVD_TYPE_LABEL: "eNVD Type",
            ENVD_STATUS_PLACEHOLDER: "Select eNVD Status",
            ENVD_STATUS_LABEL: "eNVD Status",
            EU_LABEL: "EU"

        },
        TITLE: "e-NVD",
        DESCRIPTION: "Show e-NVDs",
        HELP_LABEL: "Help",
        SEARCH_WARNING: "Please specify atleast one search criteria.",
        FILTER_CORRECT_MESSAGE: "Please correct the errors.",
        DELETE_CONFIRMATION_MESSAGE: "Are you sure you want to delete?",
        DELETE_SUCCESS: 'e-NVD record(s) deleted successfully.',
        CONSIGNMENT_SUBMIT_TO_NLIS: "e-NVD posted successfully on NLIS.",
        DELIVERY_VALIDATION_MESSAGE: 'Only In-Transit eNVD can be delivered.',

        ENVD_DELETE_COMMENT_POPUP_LABEL: 'e-NVD Delete Confirmation',
        DELETE_ENVD_COMMENT_LABEL: 'This will cancel the eNVD.',
        DELETE_ENVD_COMMENT_PLACEHOLDER: 'Comment...',
        DELIVERED_ENVD_CANNOT_DELETE: 'Delivered e-NVD cannot be deleted.',

        TRANSPORTER_CONTACT_ALREADY_ASSIGN: 'Transporter contact already assign to eNVD.',
        TRANSPORTER_COMPANY_NOT_ASSIGNED: 'Transporter company not assigned to eNVD.'

    },
    'ENVD-DETAIL': {
        TITLE: 'eNVD',
        HELP_LABEL: "Help",
        NVD_TYPE_LABEL: 'NVD Type: ',
        MLA_VERSION_LABEL: 'MLA Schema Version: ',
        MLA_API_VERSION_LABEL: 'MLA API Version: ',
        NLIS_UER_STATUS_LABEL: 'NLIS User Status: ',
        NLIS_UER_ENTERED: 'Entered',
        NLIS_UER_NOT_ENTERED: 'Not entered',
        REFERENCE_NUMBER_LABEL: 'Reference Number: ',
        SERIAL_NUMBER: 'Serial Number: ',
        COMMENCE_DATE_LABEL: 'Movement Date: ',
        CONTROLS: {
            CANCEL_LABEL: 'Cancel',
            PREVIOUS_LABEL: 'Previous',
            SAVE_LABEL: 'Save',
            NEXT_LABLE: 'Next',
            STEP1_LABEL: 'Prepare Livestock',
            STEP2_LABEL: 'Consigned to Property',
            STEP3_LABEL: 'Consigner Declaration',
            STEP4_LABEL: 'Questionnaire',
            STEP5_LABEL: 'Transporter',
            STEP6_LABEL: 'Sale Agent',
            USE_LAST_ANSWERS_LABEL: 'Use Last Answers'
        },
        SAVE_SUCCESS_MESSAGE: 'e-NVD saved succesfully',
        INVALID_ID: 'Please select valid record',
        PREPARE_LIVESTOCK: {
            TITLE: '',
            NLIS_UER_ENTERED: 'Entered',
            NLIS_UER_NOT_ENTERED: 'Not entered',
            CONTROLS: {
                EU_CATTLE_LABEL: 'EU Cattle',
                BOBBY_CALVES_LABEL: 'Bobby Calves',
                SPECIES_PLACEHOLDER: 'Select Species',
                SPECIES_LABEL: 'Species',
                SPECIES_REQ_MESSAGE: 'Please select Speices',
                CONSIGNED_FROM_PIC_PLACEHOLDER: 'Select Consigned from PIC',
                CONSIGNED_FROM_PIC_LABEL: 'Consigned from PIC',
                CONSIGNED_FROM_PIC_REQ_MESSAGE: 'Please select Consigned from PIC',
                OWNER_OF_LIVESTOCK_PLACEHOLDER: 'Enter Owner of Livestock',
                OWNER_OF_LIVESTOCK_LABEL: 'Owner of Livestock',
                OWNER_PIC_PLACEHOLDER: 'Enter Owner PIC',
                OWNER_PIC_LABEL: 'Owner PIC',
                JOURNEY_COMMENCED_ADDRESS_PLACEHOLDER: 'Enter Journey Commenced Address',
                JOURNEY_COMMENCED_ADDRESS_LABEL: 'Journey Commenced Address',
                MOB_PLACEHOLDER: 'Enter Mob Name',
                MOB_LABEL: 'Mob Name',
                MOB_REQ_MESSAGE: 'Please enter Mob Name',
                NUMBER_OF_LIVESTOCK_PLACEHOLDER: 'Enter Number Of Livestock',
                NUMBER_OF_LIVESTOCK_LABEL: 'Number Of Livestock',
                NUMBER_OF_LIVESTOCK_REQ_MESSAGE: 'Please enter Number Of Livestock',
                LIVESTOCK_DESCRIPTION_PLACEHOLDER: 'Enter Livestock Description',
                LIVESTOCK_DESCRIPTION_LABEL: 'Livestock Description',
                EAR_TAG_PLACEHOLDER: 'Enter Eartag',
                EAR_TAG_LABEL: 'Eartag',
                BRAND_PLACEHOLDER: 'Enter Brand',
                BRAND_LABEL: 'Brand',
                NUMBER_OF_EARTAGS_PLACEHOLDER: 'Enter Number Of Eartag(s)',
                NUMBER_OF_EARTAGS_LABEL: 'Number Of Eartag(s)',
                NUMBER_OF_RUMENS_PLACEHOLDER: 'Enter Number Of Rumen(s)',
                NUMBER_OF_RUMENS_LABEL: 'Number Of Rumen(s)',
                NUMBER_OF_EIDS_PLACEHOLDER: 'Enter Number Of EID(s)',
                NUMBER_OF_EIDS_LABEL: 'Number Of EID(s)'
            }
        },
        CONSIGNED_TO_PROPERTY: {
            TITLE: 'Part A - Consigned to detail',
            CONTROLS: {
                CONSIGNED_TO_PIC_PLACEHOLDER: 'Enter Consigned to PIC',
                CONSIGNED_TO_PIC_LABEL: 'Consigned to PIC',
                CONSIGNED_TO_PIC_REQ_MESSAGE: 'Please enter Consigned to PIC',
                CONSIGNED_TO_PROPERTY_NAME_PLACEHOLDER: 'Enter Property Name',
                CONSIGNED_TO_PROPERTY_NAME_LABEL: 'Property Name',
                CONSIGNED_TO_PIC_OWNER_PLACEHOLDER: 'Enter Owner of PIC',
                CONSIGNED_TO_PIC_OWNER_LABEL: 'Owner of PIC',
                CONSIGNED_TO_EMAIL_PLACEHOLDER: 'Enter Email',
                CONSIGNED_TO_EMAIL_LABEL: 'Email',
                EMAIL_VALIDATE_MESSAGE: 'Please enter valid Email',
                CONSIGNED_TO_MOBILE_PLACEHOLDER: 'Enter Mobile Number',
                CONSIGNED_TO_MOBILE_LABEL: 'Mobile Number',
                CONSIGNED_TO_FAX_PLACEHOLDER: 'Enter Fax',
                CONSIGNED_TO_FAX_LABEL: 'Fax',
                CONSIGNED_TO_ADDRESS_PLACEHOLDER: 'Enter Address',
                CONSIGNED_TO_ADDRESS_LABEL: 'Address',
                IS_DESTINATION_SAME_LABEL: 'If Destination is different than Consigned to',
                DESTINATION_PIC_PLACEHOLDER: 'Enter Destination PIC',
                DESTINATION_PIC_LABEL: 'Destination PIC',
                DESTINATION_PIC_REQ_MESSAGE: 'Please enter Destination PIC',
                DESTINATION_PROPERTY_NAME_PLACEHOLDER: 'Enter Property Name',
                DESTINATION_PROPERTY_NAME_LABEL: 'Property Name',
                DESTINATION_PIC_OWNER_PLACEHOLDER: 'Enter Owner of PIC',
                DESTINATION_PIC_OWNER_LABEL: 'Owner of PIC',
                DESTINATION_EMAIL_PLACEHOLDER: 'Enter Email',
                DESTINATION_EMAIL_LABEL: 'Email',
                DESTINATION_MOBILE_PLACEHOLDER: 'Enter Mobile Number',
                DESTINATION_MOBILE_LABEL: 'Mobile Number',
                DESTINATION_FAX_PLACEHOLDER: 'Enter Fax',
                DESTINATION_FAX_LABEL: 'Fax',
                DESTINATION_ADDRESS_PLACEHOLDER: 'Enter Address',
                DESTINATION_ADDRESS_LABEL: 'Address'
            },
            SRC_DEST_PROP_VALIDATION: 'Source and destination property cannot be same.'
        },
        CONSIGNER_DECLARER: {
            TITLE: 'Part A - Consigner Declaration',
            CONTROLS: {
                DECLARER_CONTACT_PLACEHOLDER: 'Select Responsible Person',
                DECLARER_CONTACT_LABEL: 'Name of Responsible Person',
                DECLARER_CONTACT_REQ_MESSAGE: 'Please select Responsible Person',
                DECLARER_EMAIL_PLACEHOLDER: 'Enter Email',
                DECLARER_EMAIL_LABEL: 'Email',
                EMAIL_VALIDATE_MESSAGE: 'Please enter valid Email',
                DECLARER_MOBILE_PLACEHOLDER: 'Enter Mobile Number',
                DECLARER_MOBILE_LABEL: 'Mobile Number',
                DECLARER_FAX_PLACEHOLDER: 'Enter Fax',
                DECLARER_FAX_LABEL: 'Fax',
                DECLARER_ADDRESS_PLACEHOLDER: 'Enter Address',
                DECLARER_ADDRESS_LABEL: 'Address',
                SIGNATURE_DELETE_SUCCESS: 'Signature deleted successfully.',
                PAPER_NVD_NUMBER_PLACEHOLDER: 'Enter Paper NVD Number',
                PAPER_NVD_NUMBER_LABEL: 'Paper NVD Number',
                DECLARER_ACKNOWLEDGED_LABEL: 'Acknowledged',
                ACKNOWLEDGED_DATE_PLACEHOLDER: 'Enter Signature or Acknowledged Date',
                ACKNOWLEDGED_DATE_LABEL: 'Signature or Acknowledged Date',
                DECLARATION_TEXT: 'I <b><<Resonsible Person>></b> declare that, I am the owner or the person responsible for the husbadry of the <<NVDType>> and that all the information in part A of this document is true and correct. I also declare that I have read and understand all the questions that I have answered, that I have read and understand the explanatory notes, and that, while under my control, the <<NVDType>> were not fed restricted animal material (including meat and bone meal) in breach of State or Territory legislation.'
            }
        },
        QUESTIONNAIRE: {
            TAB_LPA_LABEL: "LPA",
            TAB_NT_LABEL: "NT",
            TAB_MSA_LABEL: "MSA",
            TAB_HEALTH_LABEL: "Health",
            TAB_NFAS_LABEL: "NFAS",
            TAB_OBE_LABEL: "OBE",
            TAB_SA_LABEL: "SA",
            TAB_AUS_MEAT_LABEL: "AUS-MEAT",
            TAB_DOCUMENTS_LABEL: "Documents",
            PREV_ANSWER_REC_MESSAGE: 'Answers retrieved successfully.',
            NO_PREV_ANSWER_REC_MESSAGE: 'No eNVD is recorded previously.',
            LPA: {
                CATTLE: {
                    QUE_CTL_1: "Have any of the cattle in this consignment ever in their lives been treated with a hormonal growth promotant (HGP)?",
                    QUE_CTL_2: "Have the cattle in this consignment ever in their lives been fed feed containing animal fats?",
                    QUE_CTL_3: "Has the owner stated above owned these cattle since their birth?",
                    QUE_CTL_3_SUB: "If No, how long ago were the cattle obtained or purchased?",
                    QUE_CTL_3_SUB_1: "(If purchased at different times, tick the box corresponding to the time of the most recent purchase.)",
                    QUE_CTL_4: "In the past 60 days, have any of these cattle been fed by-product stockfeeds?",
                    QUE_CTL_4_SUB: "If Yes, attach a list of the by-product stockfeeds, date when last fed and a copy of an analyst’s report if available.",
                    BY_PRODUCT_NAME: "By-Product name",
                    BY_PRODUCT_NAME_REQ_MESSAGE: "By-Product name is required",
                    BY_PRODUCT_LAST_FED_DATE: "By-product last fed date",
                    BY_PRODUCT_LAST_FED_DATE_REQ_MESSAGE: "By-product last fed date is required",
                    BY_PRODUCT_STATEMENT: "By-product statement",
                    BY_PRODUCT_STATEMENT_REQ_MESSAGE: "By-product statement is required",
                    QUE_CTL_5: "In the past 6 months have any of these animals been on a property listed on the ERP database or placed under any restrictions because of chemical residues?",
                    QUE_CTL_5_SUB: "If Yes, give details",
                    QUE_CTL_5_SUB_INPUT_LABEL: "Enter details",
                    QUE_CTL_5_SUB_INPUT_REQ_MESSAGE: "Above details is required",
                    QUE_CTL_6: "Are any of the cattle in this consignment still within a Withholding Period (WHP) or Export Slaughter Interval (ESI) as set by APVMA or SAFEMEAT, following treatment with any veterinary drug or chemical?",
                    QUE_CTL_6_SUB: "If Yes, give details: (Record additional details in question 9)",
                    CHEMICAL_PRODUCT: "Chemical product",
                    CHEMICAL_PRODUCT_REQ_MESSAGE: "Chemical product is required",
                    TREATMENT_DATE: "Treatment date",
                    TREATMENT_DATE_REQ_MESSAGE: "Treatment date is required",
                    WHP: "WHP",
                    WHP_REQ_MESSAGE: "WHP is required",
                    ESI: "ESI (if set)",
                    QUE_CTL_7: "In the past 60 days, have any of the cattle in this consignment consumed any material that was still within a withholding period when harvested, collected or first grazed?",
                    QUE_CTL_7_SUB: "If Yes, give details",
                    DATE_APPLIED: "Date applied",
                    DATE_APPLIED_REQ_MESSAGE: "Date applied is required",
                    GRAZING_WHP: "Grazing WHP",
                    GRAZING_WHP_REQ_MESSAGE: "Grazing WHP is required",
                    DATE_FIRST_FED_GRAZED: "Date first fed/grazed",
                    DATE_FIRST_FED_GRAZED_REQ_MESSAGE: "Date first fed/grazed is required",
                    DATE_FEEDING_GRAZING_CEASED: "Date feeding/grazing ceased",
                    QUE_CTL_8: "In the past 42 days, were any of these cattle:",
                    QUE_CTL_8_1: "a) grazed in a spray risk area; or",
                    QUE_CTL_8_2: "b) fed fodders cut from a spray drift risk area?",
                    QUE_CTL_8_SUB: "If Yes Date sprayed:",
                    DATE_SPRAYED: "Date sprayed",
                    DATE_SPRAYED_REQ_MESSAGE: "Date sprayed is required",
                    QUE_CTL_9: "Additional information: see requirements in Explanatory Notes for completing this document.",
                    ADDITIONAL_INFO: "Additional information",

                    DELETE_BUTTON: "Delete",
                    ADD_BUTTON: "Add",
                    ANS_YES: "Yes",
                    ANS_NO: "No",

                    ANS_SUB_LESS2MONTHS: "Less than 2 months",
                    ANS_SUB_2TO6MONTHS: "2 - 6 months",
                    ANS_SUB_6TO12MONTHS: "6 - 12 months",
                    ANS_SUB_MORE12MONTHS: "More than 12 months"

                },
                EUCATTLE: {
                    QUE_1: "Have the cattle in this consignment ever in their lives been fed feed containing animal fats?",
                    QUE_2: "Were all of the cattle born and raised on the vendor's property?",
                    QUE_2_SUB: "If No, how long ago were the cattle obtained or purchased?",
                    QUE_2_SUB_1: "(If purchased at different times, tick the box corresponding to the time of the most recent purchase.)",
                    QUE_3: "In the past 60 days, have any of these cattle been fed by-product stockfeeds?",
                    QUE_3_SUB: "If Yes, attach a list of the by-product stockfeeds, date when last fed and a copy of an analyst’s report if available.",
                    BY_PRODUCT_NAME: "By-Product name",
                    BY_PRODUCT_NAME_REQ_MESSAGE: "By-Product name is required",
                    BY_PRODUCT_LAST_FED_DATE: "By-product last fed date",
                    BY_PRODUCT_LAST_FED_DATE_REQ_MESSAGE: "By-product last fed date is required",
                    BY_PRODUCT_STATEMENT: "By-product statement",
                    BY_PRODUCT_STATEMENT_REQ_MESSAGE: "By-product statement is required",
                    QUE_4: "In the past 6 months, have any of these cattle been on a property listed on the ERP database or placed under grazing restrictions because of chemical residue?",
                    QUE_4_SUB: "If Yes, give details",
                    QUE_4_SUB_INPUT_LABEL: "Enter details",
                    QUE_4_SUB_INPUT_REQ_MESSAGE: "Above details is required",
                    QUE_5: "Are any of the cattle in this consignment still within a Withholding Period (WHP) or Export Slaughter Interval (ESI) as set by APVMA or SAFEMEAT, following treatment with any veterinary drug or chemical?",
                    QUE_5_SUB: "If Yes, give details: (Record additional details in question 8)",
                    CHEMICAL_PRODUCT: "Chemical product",
                    CHEMICAL_PRODUCT_REQ_MESSAGE: "Chemical product is required",
                    TREATMENT_DATE: "Treatment date",
                    TREATMENT_DATE_REQ_MESSAGE: "Treatment date is required",
                    WHP: "WHP",
                    WHP_REQ_MESSAGE: "WHP is required",
                    ESI: "ESI (if set)",
                    QUE_6: "In the past 60 days, have any of the cattle in this consignment consumed any material that was still within a withholding period when harvested, collected or first grazed?",
                    QUE_6_SUB: "If Yes, give details",
                    DATE_APPLIED: "Date applied",
                    DATE_APPLIED_REQ_MESSAGE: "Date applied is required",
                    GRAZING_WHP: "Grazing WHP",
                    GRAZING_WHP_REQ_MESSAGE: "Grazing WHP is required",
                    DATE_FIRST_FED_GRAZED: "Date first fed/grazed",
                    DATE_FIRST_FED_GRAZED_REQ_MESSAGE: "Date first fed/grazed is required",
                    DATE_FEEDING_GRAZING_CEASED: "Date feeding/grazing ceased",

                    QUE_7: "In the past 42 days, were any of these cattle:",
                    QUE_7_1: "a) grazed in a spray risk area; or b) fed fodders cut from a spray drift risk area? (See Explanatory Notes for definition of spray drift risk area.)",
                    QUE_7_SUB: "If Yes Date sprayed",
                    DATE_SPRAYED: "Date sprayed",
                    DATE_SPRAYED_REQ_MESSAGE: "Date sprayed is required",
                    QUE_8: "Additional information: see requirements in Explanatory Notes for completing this document.",
                    ADDITIONAL_INFO: "Additional information",

                    DELETE_BUTTON: "Delete",
                    ADD_BUTTON: "Add",
                    ANS_YES: "Yes",
                    ANS_NO: "No",

                    ANS_SUB_LESS2MONTHS: "Less than 2 months",
                    ANS_SUB_2TO6MONTHS: "2 - 6 months",
                    ANS_SUB_6TO12MONTHS: "6 - 12 months",
                    ANS_SUB_MORE12MONTHS: "More than 12 months"

                },
                BOBBYCALVES: {
                    QUE_1: "Have these calves been raised on a licensed dairy farm or consistent with the rules of an independently audited QA program on the property the PIC of which is shown above?",
                    QUE_1_SUB: "If Yes, give details",
                    PROGRAM_NAME: "Name of program",
                    PROGRAM_NAME_REQ_MESSAGE: "Please enter Name of program",
                    ACCRED_LICENSE_NO: "Accreditation or license no.",
                    ACCRED_LICENSE_NO_REQ_MESSAGE: "Please enter Name of program",

                    QUE_2: "Has the owner stated above owned these calves since their birth?",
                    QUE_2_SUB: "If No, how long ago were the calves obtained or purchased?",
                    QUE_3: "In the past 60 days, have any of the calves in this consignment consumed any material that was still within a withholding period when harvested, collected or first grazed?",
                    QUE_3_SUB: "If Yes, give details",
                    CHEMICAL_PRODUCT: "Chemical product",
                    CHEMICAL_PRODUCT_REQ_MESSAGE: "Chemical product is required",
                    DATE_APPLIED: "Date applied",
                    DATE_APPLIED_REQ_MESSAGE: "Date applied is required",
                    GRAZING_WHP: "Grazing WHP",
                    GRAZING_WHP_REQ_MESSAGE: "Grazing WHP is required",
                    DATE_FIRST_FED_GRAZED: "Date first fed/grazed",
                    DATE_FIRST_FED_GRAZED_REQ_MESSAGE: "Date first fed/grazed is required",
                    DATE_FEEDING_GRAZING_CEASED: "Date feeding/grazing ceased",

                    QUE_4: "Have any of the calves in this consignment been treated orally, externally or by injection with a veterinary drug or chemical, including medicated feeds?",
                    QUE_4_SUB: "If Yes, list details in the following space provided",
                    VETERINARY_DRUG_CHEMICAL_PRODUCT: "Veterinary drug/Chemical",
                    VETERINARY_DRUG_CHEMICAL_PRODUCT_REQ_MESSAGE: "Veterinary drug/Chemical is required",
                    TREATMENT_DATE: "Calf Treatment date",
                    TREATMENT_DATE_REQ_MESSAGE: "Calf Treatment date is required",
                    WHP: "Meat WHP (days)",
                    WHP_REQ_MESSAGE: "Meat WHP is required",
                    ESI: "ESI (if set)",

                    QUE_5: "Have any of the calves in this consignment had access to milk from cows that had been treated orally, externally or by intramammary, intramuscular or subcutaneous injection veterinary drug or chemical, before the milk withholding period has expired?",
                    QUE_5_SUB: "If Yes, list details in the following space provided",
                    QUE_6: "In the past 6 months have any of these animals been on a property listed on the ERP database or placed under any restrictions because of chemical residues?",
                    QUE_6_SUB: "If Yes, give details",
                    QUE_6_SUB_INPUT_LABEL: "Enter details",
                    QUE_6_SUB_INPUT_REQ_MESSAGE: "Above details is required",
                    QUE_7: "Additional information",
                    ADDITIONAL_INFO: "Additional information",

                    DELETE_BUTTON: "Delete",
                    ADD_BUTTON: "Add",
                    ANS_YES: "Yes",
                    ANS_NO: "No",

                    ANS_SUB_LESS1WEEK: "Less than 1 week",
                    ANS_SUB_MORE1WEEK: "More than 1 week"

                },
                GOAT: {
                    QUE_GOAT_A: "Have PICs on all NLIS tags in this consignment been listed in the Description table above (other than the PIC printed on this NVD)?",
                    QUE_GOAT_B: "Have all goats in this consignment been tagged with an additional pink post breeder tag with the PIC printed on this NVD? (or WA brand as listed in the Description table above)?",
                    QUE_GOAT_1: "Were all of these goats bred by the owner or vendor?",
                    QUE_GOAT_1_SUB: "If No, how long ago were the goats obtained or purchased?",
                    QUE_GOAT_2: "Have all the goats in this consignment been grown under rangeland conditions?",
                    QUE_GOAT_3: "Are any of the goats in this consignment still within a Withholding Period (WHP) or Export Slaughter Interval (ESI) as set by APVMA or SAFEMEAT, following treatment with any registered veterinary drug or chemical?",
                    QUE_GOAT_3_SUB: "If Yes, give details: (Record additional details in question 6)",
                    CHEMICAL_PRODUCT: "Chemical product",
                    CHEMICAL_PRODUCT_REQ_MESSAGE: "Chemical product is required",
                    TREATMENT_DATE: "Treatment date",
                    TREATMENT_DATE_REQ_MESSAGE: "Treatment date is required",
                    WHP: "WHP",
                    WHP_REQ_MESSAGE: "WHP is required",
                    ESI: "ESI (if set)",
                    QUE_GOAT_4: "In the past 60 days, have any of these goats consumed any material that was still within a withholding period when harvested, collected or first grazed?",
                    QUE_GOAT_4_SUB: "If Yes, give details",
                    DATE_APPLIED: "Date applied",
                    DATE_APPLIED_REQ_MESSAGE: "Date applied is required",
                    GRAZING_WHP: "Grazing WHP",
                    GRAZING_WHP_REQ_MESSAGE: "Grazing WHP is required",
                    DATE_FIRST_FED_GRAZED: "Date first fed/grazed",
                    DATE_FIRST_FED_GRAZED_REQ_MESSAGE: "Date first fed/grazed is required",
                    DATE_FEEDING_GRAZING_CEASED: "Date feeding/grazing ceased",
                    QUE_GOAT_5: "Have the goats in this consignment ever in their lives been fed feed containing animal fats?",
                    QUE_GOAT_6: "Please include any additional information below",
                    QUE_GOAT_6_1: "eg: vaccination programs, animal health certification, additional declarations, etc.",

                    DELETE_BUTTON: "Delete",
                    ADD_BUTTON: "Add",
                    ANS_YES: "Yes",
                    ANS_NO: "No",

                    ANS_SUB_LESS2MONTHS: "Less than 2 months",
                    ANS_SUB_2TO6MONTHS: "2 - 6 months",
                    ANS_SUB_6TO12MONTHS: "6 - 12 months",
                    ANS_SUB_MORE12MONTHS: "More than 12 months"
                },
                SHEEP: {
                    QUE_SHEEP_A: "Have PICs on all NLIS tags in this consignment been listed in the Description table above (other than the PIC selected on this NVD)?",
                    QUE_SHEEP_B: "Have all sheep in this consignment been tagged with an additional pink post breeder tag with the PIC printed on this NVD (or WA brand as listed in the description table above)?",
                    QUE_SHEEP_C: "Hours off feed and water before transporting",
                    HOURS_OFF_FEED_WATER: 'Hours off feed and water before transporting',
                    HOURS_OFF_FEED_WATER_REQ_MESSAGE: "Please enter Hours off feed and water before transporting",
                    QUE_SHEEP_1: "Have these sheep or lambs been raised consistent with the rules of an independently audited QA program on the property the PIC of which is shown above?",
                    QUE_SHEEP_1_SUB: "If Yes, give details",
                    PROGRAM_NAME: "Name of program",
                    PROGRAM_NAME_REQ_MESSAGE: "Please enter Name of program",
                    ACCRED_LICENSE_NO: "Accreditation or license no.",
                    ACCRED_LICENSE_NO_REQ_MESSAGE: "Please enter Name of program",
                    QUE_SHEEP_2: "Have all the sheep or lambs in this consignment been treated with a Scabby Mouth Vaccination either at marking or at least 14 days prior to their presentation for sale?",
                    QUE_SHEEP_3: "Were all of these goats bred by the owner or vendor?",
                    QUE_SHEEP_3_SUB: "If No, how long ago were the sheeps obtained or purchased?",
                    QUE_SHEEP_4: "Are any of the sheep or lambs in this consignment still within a Withholding Period (WHP) or Export Slaughter Interval (ESI) as set by APVMA or SAFEMEAT, following treatment with any veterinary drug or chemical?",
                    QUE_SHEEP_4_SUB: "If Yes, give details: (Record additional details in question 7)",
                    CHEMICAL_PRODUCT: "Chemical product",
                    CHEMICAL_PRODUCT_REQ_MESSAGE: "Chemical product is required",
                    TREATMENT_DATE: "Treatment date",
                    TREATMENT_DATE_REQ_MESSAGE: "Treatment date is required",
                    WHP: "WHP",
                    WHP_REQ_MESSAGE: "WHP is required",
                    ESI: "ESI (if set)",
                    QUE_SHEEP_5: "In the past 60 days, have any of the sheep or lambs in this consignment consumed any material that was still within a withholding period when harvested, collected or first grazed?",
                    QUE_SHEEP_5_SUB: "If Yes, give details",
                    DATE_APPLIED: "Date applied",
                    DATE_APPLIED_REQ_MESSAGE: "Date applied is required",
                    GRAZING_WHP: "Grazing WHP",
                    GRAZING_WHP_REQ_MESSAGE: "Grazing WHP is required",
                    DATE_FIRST_FED_GRAZED: "Date first fed/grazed",
                    DATE_FIRST_FED_GRAZED_REQ_MESSAGE: "Date first fed/grazed is required",
                    DATE_FEEDING_GRAZING_CEASED: "Date feeding/grazing ceased",
                    DATE_FEEDING_GRAZING_CEASED_REQ_MESSAGE: "Date feeding/grazing ceased is required",

                    QUE_SHEEP_6: "Have the sheep or lambs in this consignment ever in their lives been fed feed containing animal fats?",
                    QUE_SHEEP_7: "Please include any additional information below",
                    QUE_SHEEP_7_1: "eg: vaccination programs, animal health certification, additional declarations, etc.",

                    DELETE_BUTTON: "Delete",
                    ADD_BUTTON: "Add",
                    ANS_YES: "Yes",
                    ANS_NO: "No",

                    ANS_SUB_LESS2MONTHS: "Less than 2 months",
                    ANS_SUB_2TO6MONTHS: "2 - 6 months",
                    ANS_SUB_6TO12MONTHS: "6 - 12 months",
                    ANS_SUB_MORE12MONTHS: "More than 12 months"
                }
            },
            NT: {
                CHEMICAL_PRODUCT_LABEL: "Chemical Product",
                CHEMICAL_PRODUCT_PLACEHOLDER: "Type to search Chemical Product",
                TREATMENT_METHOD_LABEL: "Treatment Method",
                TREATMENT_METHOD_PLACEHOLDER: "Type to search Treatment Method",

                LAST_ACCESS_TO_WATER: "Last access to water",
                BIOSECURITY_OFFICER_PLACEHOLDER: "Start typing to search",
                BIOSECURITY_OFFICER_LABEL: "Name of livestock biosecurity officer",
                MOVEMENT_TO_AREA_PLACEHOLDER: "Enter Movement to area",
                MOVEMENT_TO_AREA_LABEL: "Movement to area",
                MOVEMENT_FOR_PLACEHOLDER: "Enter Movement for",
                MOVEMENT_FOR_LABEL: "Movement for",
                SIGNATURE: "Signature",
                SIGNATURE_DATE: "Signature date",
                PHONE_NUMBER_PLACEHOLDER: "Enter Phone Number",
                PHONE_NUMBER_LABEL: "Phone Number",
                SIGNATURE_DELETE_SUCCESS: "Signature deleted successfully."
            },
            HEALTH: {
                QUE_1: "Bovine Respiratory Disease(BRD), details of the Bovillis MH+IBR vaccine",
                QUE_1_SUB: "If Yes, give details:",
                BOTTLE_ID: "Bottle Identification",
                BOTTLE_ID_REQ_MESSAGE: "Please enter Bottle Identification",
                BATCH_NO: "Batch No",
                BATCH_NO_REQ_MESSAGE: "Please enter Batch No",
                EXPIRY_DATE: "Expiry date",
                EXPIRY_DATE_REQ_MESSAGE: "Please select Expiry date",

                ANS_YES: "Yes",
                ANS_NO: "No",
            },
            MSA: {
                QUE_1: "Are all animals in this lot milk fed vealers?",
                QUE_1_SUB: "(To qualify as milk fed vealers, calves must still be suckling and must be sent direct to slaughter)",
                QUE_2: "Has this lot of cattle been sold through an MSA accredited saleyard program?",
                QUE_3: "Tick the highest tropical breed (or Bos Indicus) content of this lot",
                COMMENT: "Comment",

                ZERO: '0% eg Hereford or Angus',
                LESS13: 'Less than 13%',
                LESS20: 'Less than 20%',
                LESS26: 'Less than 26%',
                LESS39: 'Less than 39% eg Santa Gertrudis',
                LESS51: 'Less than 51% eg Braford',
                LESS76: 'Less than 76%',
                UPTO100: 'Up to and including 100% eg Brahman',

                ANS_YES: "Yes",
                ANS_NO: "No",
            },
            AUSMEAT: {
                LIVESTOCK_DECLARATION_LABEL: "LIVESTOCK Declaration Q.A. OFFICER TO COMPLETE",
                ABATTOIR_TO_COMPLETE_LABEL: "ABATTOIR TO COMPLETE",

                LINE_1: "I declare that the livestock detailed above have been fed at an AUS-MEAT Accredited Livestock Prodiction System for",
                LINE_2: "days on a nutritionally balanced ration which conforms to the AUS-MEAT approved specification for the type of livestock described above; and that there is no reason to believe the livestock that are the subject of this LPAS Delivery Docket, have at any time during their life been treated with or exposed to any chemical, substance or other material that would render the animals unsuitable for production.",

                LINE_3: "Original docket to be retained by abattoir for 18 months from date of slaughter",
                LINE_4: "# This docket is valid for seven (7) days from the date livestock are",
                LINE_5: "taken off the AUS-MEAT Accredited livestock prodiction system.",
                LINE_6: "The statement above assumes all animal welfare requirements are met.",

                SIGNATURE: "Signature",
                DATE: "Date",
                RECORD_DAYS: "Record Number of Days",
                NAME: "Name of Q.A. Officer (Print)",
                SLAUGHTER_DATE: "Date of slaughter",

                SIGNATURE_DELETE_SUCCESS: "Signature deleted successfully."
            },
            NFAS: {
                QUE_1: "The Cattle have been fed at an NFAS Accredited Feelot for not less than",
                DOF: 'The number of days on feed (DOF) as stated in the Cattle Description section. The Cattle described above are being transferred for on-feeding at another NFAS Accredited Feedlot.',
                Days60: '60 days (heifer only), at least 50 days of which',
                Days70: '70 days, at least 60 days of which',
                Days100: '100 days, at least 80 days of which',

                DECLARATION: "DECLARATION (ONLY TO BE COMPLETED BY A QA OFFICER)",
                NAME: "Name(Print)",
                CERTIFICATE_NO: "Certificate No",
                SIGNATURE: "Signature",
                DATE: "Date",
                SLAUGHTER_DATE: "Date of slaughter",

                DENTITION_PLACEHOLDER: "Select Dentition",
                DENTITION_LABEL: "Dentition",
                MINIMUM_DAYS_ON_FEED_PLACEHOLDER: "Eneter Minimum Days On Feed",
                MINIMUM_DAYS_ON_FEED_LABEL: "Minimum Days On Feed",

                SIGNATURE_DELETE_SUCCESS: "Signature deleted successfully."
            },
            OBE: {
                OBE_ORGANIC: "OBE Organic"
            },
            DOCUMENTS: {
                DOC_FILE_LABEL: "Document File",
                DOC_TYPE: "Document Type",
                DOC_NO: "Document No",
                OFFICE_OF_ISSUE: "Office Of Issue",
                EXPIRY_DATE: "Expiry Date",

                ADD_LABEL: "Add",
                CLEAR_LABEL: "Clear"
            },
            SA: {
                TATTOO_DELETE_SUCCESS: "Prefix tattoo deleted successfully."
            }
        },
        TRANSPORTER: {
            TITLE: 'Part B - Transporter Detail',
            CONTROLS: {
                SUB_TITLE: 'Transporting By',
                TRANSPORTER_RADIO_LABEL: 'Transporter',
                CONSIGNER_RADIO_LABEL: 'Consigner',
                CONSIGNEE_RADIO_LABEL: 'Consignee',
                NEW_TRANSPORTER_RADIO_LABEL: 'New Transporter',
                TRANSPORTER_COMAPNY_NAME_PLACEHOLDER: 'Select Transporter Company/Business Unit',
                TRANSPORTER_COMAPNY_NAME_LABEL: 'Transporter Company/Business Unit',
                TRANSPORTER_NAME_PLACEHOLDER: 'Select Transporter',
                TRANSPORTER_NAME_LABEL: 'Transporter',
                TRANSPORTER_NAME_REQ_MESSAGE: 'Plesae Select Transporter',
                TRANSPORTER_FIRST_NAME_PLACEHOLDER: 'Enter Transporter First Name',
                TRANSPORTER_FIRST_NAME_LABEL: 'Transporter First Name',
                TRANSPORTER_FIRST_NAME_REQ_MESSAGE: 'Please enter Transporter First Name',
                TRANSPORTER_LAST_NAME_PLACEHOLDER: 'Enter Transporter Last Name',
                TRANSPORTER_LAST_NAME_LABEL: 'Transporter Last Name',
                TRANSPORTER_LAST_NAME_REQ_MESSAGE: 'Please enter Transporter Last Name',
                DRIVER_NAME_PLACEHOLDER: 'Enter Driver Name',
                DRIVER_NAME_LABEL: 'Driver Name',
                DRIVER_NAME_REQ_MESSAGE: 'Please enter Driver Name',
                VEHICLE_REGO_NUMBER_PLACEHOLDER: 'Enter Vehicle Rego Number',
                VEHICLE_REGO_NUMBER_LABEL: 'Vehicle Rego Number',
                ADDITIONAL_VEHICLE_REGO_PLACEHOLDER: 'Enter Additional Vehicle Rego Number',
                ADDITIONAL_VEHICLE_REGO_LABEL: 'Additional Vehicle Rego Number',
                COMPANY_NAME_PLACEHOLDER: 'Enter Company Name',
                COMPANY_NAME_LABEL: 'Company Name',
                TELEPHONE_PLACEHOLDER: 'Enter Telephone',
                TELEPHONE_LABEL: 'Telephone',
                EMAIL_PLACEHOLDER: 'Enter Email',
                EMAIL_LABEL: 'Email',
                EMAIL_VALIDATE_MESSAGE: 'Please enter valid Email',
                MOBILE_NUMBER_PLACEHOLDER: 'Enter Mobile Number',
                MOBILE_NUMBER_LABEL: 'Mobile Number',
                FAX_PLACEHOLDER: 'Enter Fax',
                FAX_LABEL: 'Fax',
                ADDRESS_PLACEHOLDER: 'Enter Addreess',
                ADDRESS_LABEL: 'Addreess',
                TRANSPORTER_ACKNOWLEDGED_LABEL: 'Acknowledged',
                ACKNOWLEDGED_DATE_PLACEHOLDER: 'Enter Signature or Acknowledged Date',
                ACKNOWLEDGED_DATE_LABEL: 'Signature or Acknowledged Date',
                MOVEMENT_DATE_PLACEHOLDER: 'Enter Movement Commence Date',
                MOVEMENT_DATE_LABEL: 'Movement Commence Date',
                DECLARATION_TEXT: 'I am <strong><<Driver Name>></strong> the person in charge of the <<NVDType>> during the movement and declare all the information in Part B is true and correct.'
            }
        },
        SALE_AGENT: {
            TITLE: 'Part C - Sale Agent Detail',
            CONTROLS: {
                SALE_AGENT_COMAPNY_NAME_PLACEHOLDER: 'Select Sale Agent Company/Business Unit',
                SALE_AGENT_COMAPNY_NAME_LABEL: 'Sale Agent Company/Business Unit',
                SALE_AGENT_NAME_PLACEHOLDER: 'Select Sale Agent',
                SALE_AGENT_NAME_LABEL: 'Sale Agent',
                SALE_AGENT_FIRST_NAME_PLACEHOLDER: 'Enter Sale Agent First Name',
                SALE_AGENT_FIRST_NAME_LABEL: 'Sale Agent First Name',
                SALE_AGENT_LAST_NAME_PLACEHOLDER: 'Enter Sale Agent Last Name',
                SALE_AGENT_LAST_NAME_LABEL: 'Sale Agent Last Name',
                SALE_AGENT_CODE_PLACEHOLDER: 'Enter Sale Agent Code',
                SALE_AGENT_CODE_LABEL: 'Sale Agent Code',
                SALE_AGENT_VENDOR_PLACEHOLDER: 'Enter Sale Agent Vendor Code',
                SALE_AGENT_VENDOR_LABEL: 'Sale Agent Vendor Code',
                COMPANY_NAME_PLACEHOLDER: 'Enter Company Name',
                COMPANY_NAME_LABEL: 'Company Name',
                TELEPHONE_PLACEHOLDER: 'Enter Telephone',
                TELEPHONE_LABEL: 'Telephone',
                EMAIL_PLACEHOLDER: 'Enter Email',
                EMAIL_LABEL: 'Email',
                EMAIL_VALIDATE_MESSAGE: 'Please enter valid Email',
                MOBILE_NUMBER_PLACEHOLDER: 'Enter Mobile Number',
                MOBILE_NUMBER_LABEL: 'Mobile Number',
                FAX_PLACEHOLDER: 'Enter Fax',
                FAX_LABEL: 'Fax',
                ADDRESS_PLACEHOLDER: 'Enter Addreess',
                ADDRESS_LABEL: 'Addreess',
                SALE_AGENT_ACKNOWLEDGED_LABEL: 'Acknowledged',
                ACKNOWLEDGED_DATE_PLACEHOLDER: 'Enter Signature or Acknowledged Date',
                ACKNOWLEDGED_DATE_LABEL: 'Signature or Acknowledged Date',
                NEW_SALE_AGENT_LABEL: 'New Sale Agent'
            }
        }
    },
    'PICKUP': {
        TITLE: 'Pickup eNVD',
        NVD_TYPE_LABEL: 'NVD Type: ',
        MLA_VERSION_LABEL: 'MLA Schema Version: ',
        MLA_API_VERSION_LABEL: 'MLA API Version: ',
        NLIS_USER_STATUS_LABEL: 'NLIS User Status: ',
        REFERENCE_NUMBER_LABEL: 'Reference Number: ',
        SERIAL_NUMBER_LABEL: 'Serial Number: ',
        MOVEMENT_COMMENCE_DATE_LABEL: 'Movement Commence Date: ',

        CONTROLS: {
            CANCEL_LABEL: 'Cancel',
            SAVE_LABEL: 'Save'
        },
        SAVE_SUCCESS_MESSAGE: 'e-NVD saved succesfully',
        INVALID_ID: 'Please select valid record',
        TRANSPORTER_REQ: 'Please select transporter.',
        TRANSPORTER: {
            TITLE: 'Part B - Transporter Detail',
            CONTROLS: {
                SUB_TITLE: 'Transporting By',
                TRANSPORTER_RADIO_LABEL: 'Transporter',
                CONSIGNER_RADIO_LABEL: 'Consigner',
                CONSIGNEE_RADIO_LABEL: 'Consignee',
                NEW_TRANSPORTER_RADIO_LABEL: 'New Transporter',
                TRANSPORTER_COMAPNY_NAME_PLACEHOLDER: 'Select Transporter Company/Business Unit',
                TRANSPORTER_COMAPNY_NAME_LABEL: 'Transporter Company/Business Unit',
                TRANSPORTER_NAME_PLACEHOLDER: 'Select Transporter',
                TRANSPORTER_NAME_LABEL: 'Transporter',
                TRANSPORTER_NAME_REQ_MESSAGE: 'Plesae Select Transporter',
                TRANSPORTER_FIRST_NAME_PLACEHOLDER: 'Enter Transporter First Name',
                TRANSPORTER_FIRST_NAME_LABEL: 'Transporter First Name',
                TRANSPORTER_FIRST_NAME_REQ_MESSAGE: 'Please enter Transporter First Name',
                TRANSPORTER_LAST_NAME_PLACEHOLDER: 'Enter Transporter Last Name',
                TRANSPORTER_LAST_NAME_LABEL: 'Transporter Last Name',
                TRANSPORTER_LAST_NAME_REQ_MESSAGE: 'Please enter Transporter Last Name',
                DRIVER_NAME_PLACEHOLDER: 'Enter Driver Name',
                DRIVER_NAME_LABEL: 'Driver Name',
                DRIVER_NAME_REQ_MESSAGE: 'Please enter Driver Name',
                VEHICLE_REGO_NUMBER_PLACEHOLDER: 'Enter Vehicle Rego Number',
                VEHICLE_REGO_NUMBER_LABEL: 'Vehicle Rego Number',
                ADDITIONAL_VEHICLE_REGO_PLACEHOLDER: 'Enter Additional Vehicle Rego Number',
                ADDITIONAL_VEHICLE_REGO_LABEL: 'Additional Vehicle Rego Number',
                COMPANY_NAME_PLACEHOLDER: 'Enter Company Name',
                COMPANY_NAME_LABEL: 'Company Name',
                TELEPHONE_PLACEHOLDER: 'Enter Telephone',
                TELEPHONE_LABEL: 'Telephone',
                EMAIL_PLACEHOLDER: 'Enter Email',
                EMAIL_LABEL: 'Email',
                MOBILE_NUMBER_PLACEHOLDER: 'Enter Mobile Number',
                MOBILE_NUMBER_LABEL: 'Mobile Number',
                FAX_PLACEHOLDER: 'Enter Fax',
                FAX_LABEL: 'Fax',
                ADDRESS_PLACEHOLDER: 'Enter Addreess',
                ADDRESS_LABEL: 'Addreess',
                TRANSPORTER_ACKNOWLEDGED_LABEL: 'Acknowledged',
                ACKNOWLEDGED_DATE_PLACEHOLDER: 'Enter Signature or Acknowledged Date',
                ACKNOWLEDGED_DATE_LABEL: 'Signature or Acknowledged Date',
                MOVEMENT_DATE_PLACEHOLDER: 'Enter Movement Commence Date',
                MOVEMENT_DATE_LABEL: 'Movement Commence Date',
                DECLARATION_TEXT: 'I am <strong><<Driver Name>></strong> the person in charge of the <<NVDType>> during the movement and declare all the information in Part B is true and correct.'
            }
        }
    },
    'DELIVERY': {
        TITLE: 'Deliver eNVD',
        NLIS_UER_ENTERED: 'Entered',
        NLIS_UER_NOT_ENTERED: 'Not entered',
        CONTROLS: {
            CANCEL_LABEL: 'Cancel',
            SAVE_LABEL: 'Save',
            IMPORT_CSV_LABEL: 'Import CSV',
            NVD_TYPE_LABEL: 'NVD Type: ',
            MLA_VERSION_LABEL: 'MLA Schema Version: ',
            MLA_API_VERSION_LABEL: 'MLA API Version: ',
            NLIS_UER_STATUS_LABEL: 'NLIS User Status: ',
            REFERENCE_NUMBER_LABEL: 'Reference Number: ',
            SERIAL_NUMBER: 'Serial Number: ',
            COMMENCE_DATE_LABEL: 'Movement Date: ',
            DELIVERY_DATE_PLACEHOLDER: 'Select Date of Delivery',
            DELIVERY_DATE_LABEL: 'Date of Delivery',
            TOTAL_LIVESTOCK_PLACEHOLDER: 'Number of livestock in consignment',
            TOTAL_LIVESTOCK_LABEL: 'Number of livestock in consignment',
            DELIVERY_LIVESTOCK_PLACEHOLDER: 'Enter Number of livestick in delivery',
            DELIVERY_LIVESTOCK_LABEL: 'Number of livestick in delivery',
            SUSPECT_QUANTITY_PLACEHOLDER: 'Enter Suspect Quantity',
            SUSPECT_QUANTITY_LABEL: 'Suspect Quantity',
            CONDEMNED_QUANTITY_PLACEHOLDER: 'Enter Condemned Quantity',
            CONDEMNED_QUANTITY_LABEL: 'Condemned Quantity',
            ENCLOSURE_PLACEHOLDER: 'Select Enclosure',
            ENCLOSURE_LABEL: 'Enclosure',
            ENCLOSURE_REQ_MESSAGE: 'Please select Enclosure',
            ENCLOSURE_TYPE_PLACEHOLDER: 'Select Enclosure Type',
            ENCLOSURE_TYPE_LABEL: 'Enclosure Type',
            ENCLOSURE_TYPE_REQ_MESSAGE: 'Please select Enclosure Type',
            ENCLOSURE_NAME_PLACEHOLDER: 'Enter Enclosure Name',
            ENCLOSURE_NAME_LABEL: 'Enclosure Name',
            ENCLOSURE_NAME_REQ_MESSAGE: 'Please enter Enclosure Name',
            WELFARE_ACTIVITY_PLACEHOLDER: 'Enter Welfare Activity',
            WELFARE_ACTIVITY_LABEL: 'Welfare Activity',
            WELFARE_ACTIVITY_TIME_PLACEHOLDER: 'Select Welfare Activity Time',
            WELFARE_ACTIVITY_TIME_LABEL: 'Welfare Activity Time',
            COMMENT_PLACEHOLDER: 'Enter Comment',
            COMMENT_LABEL: 'Comment',
            GPS_PLACEHOLDER: 'Select GPS',
            GPS_LABEL: 'GPS',
            CREATE_ENCLOSURE_LABEL: 'Create Enclosure'
        },
        INVALID_ID: 'Please select valid record',
        DELIVERY_DATE_INVALID_MESSAGE: 'Date of delivery must be after movement commence date.',
        WELFARE_ACTIVITY_TIME_INVALID_MESSAGE: 'Welfare activity time must be between movement commence date and delivery date.',
        VARIANCE_DETAIL_REQ_MESSAGE: 'Please upload CSV for variance livestock detail.',
        VARIANCE_MISSMATCH: 'Variance quantity in form and CSV not match.',
        SUCCESS_MESSAGE: 'e-NVD Delivered Successfully.',
        IMPORT_CSV_VALIDATION: 'Please import valid csv to update delivery.',
        IMPORT_POPUP: {
            TITLE: 'Import Livestock',
            STEP1: 'Upload CSV',
            STEP2: 'Map CSV Data',
            STEP3: 'Result',
            CONTROLS: {
                VALIDATE_LABEL: 'Validate',
                FINISH_LABEL: 'Finish',
                PREVIOUS_LABEL: 'Previous',
                NEXT_LABLE: 'Next',
                UPLOAD_CSV_LABEL: 'Upload CSV',
                LIVESTOCKIDENTIFIER_PLACEHOLDER: 'Select Livetock Identifier',
                LIVESTOCKIDENTIFIER_LABEL: 'Livetock Identifier',
                LIVESTOCKIDENTIFIER_REQ_MESSAGE: 'Please select Livetock Identifier',
                VARIANCE_IMPORT_LABEL: 'Import variance livestock',
                DELIVERED_IMPORT_LABEL: 'Import delivered livestock'
            },
            UPLOAD_FILE_VALIDAITON_MESSAGE: 'Please upload CSV file to import data.',
            VALIDATION_REQ_MESSASAGE: 'Please validate data first.',
            INVALID_CSV: 'CSV contains invalid data. Please upload CSV with valid data to update delivery.',
            VALID_CSV: 'CSV uploaded successfully, continue with update delivery.',
            VALIDATE_SUCCESS: 'CSV validated successfully.'
        }
    }
}